variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

default:
  image: python:3.8

before_script:
  - python --version
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install xattr

stages:
  - Static Analysis
  - Tests

flake8:
  stage: Static Analysis
  script:
    - pip3 install flake8
    - flake8

mypy:
  stage: Static Analysis
  script:
    - pip3 install mypy
    - mypy -p fake_super

.test:
  stage: Tests
  script:
    - pip3 install nose coverage mock
    - nosetests

test-3.6:
  extends: .test
  image: python:3.6

test-3.7:
  extends: .test
  image: python:3.7

test-3.8:
  extends: .test
  image: python:3.8
  artifacts:
    reports:
      cobertura: coverage.xml
